name: Go

on: [push, pull_request]

env:
  DARWIN_AMD64_BINARY: "toolbox-darwin-amd64"
  DARWIN_ARM64_BINARY: "toolbox-darwin-arm64"
  LINUX_AMD64_BINARY: "toolbox-linux-amd64"
  LINUX_ARM64_BINARY: "toolbox-linux-arm64"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run:
        - make dep
        - mkdir -p build
        - make build

    - name: Test
      run:
        - make dep
        - make test
        - make test-integration